### ISSUE TITLE
Goldsmith plan evaluation shortcomings

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-goldsmith#43] opened 2020-12-18 10:22 UTC
- Client provided during event evaluation only has general information. We need LMP(current ga) and last/current contact information to schedule  the next ANC contact correctly. The scheduling is dependent on the gestation age since scheduling is different and not directly dependent on the contact no. The ANC contact no is dependent on the last contact number. These two should either be provided in the event or the client.

**Comment by ekigamba** [comment] 2021-02-04 06:55
This seems to be a duplicate of https://github.com/OpenSRP/opensrp-client-goldsmith/issues/39

**Comment by githengi** [comment] 2021-02-05 06:40
duplicate of #39

**Closed as completed by githengi** 2021-02-05 06:40 UTC
Labels: tech-debt
